language: python
python:
  - "3.8"
install:
  - conda create -n assignment1
  - conda activate accignment1
  - conda install -c conda-forge pygraphblas 
  - pip install -r requirements.txt
script:
  - pytest tests/main.py
